# default configuration
baseURL = "http://examplesite.com"
languageCode = "en-us"
summaryLength = "10"
title = "IIIT-H Astronomy Club"

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/fontawesome/fontawesome.min.css"
[[params.plugins.css]]
URL = "plugins/custom/css/style.css"

# js plugin
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

[[menu.main]]
URL = "events"
name = "Events"
weight = 2

[[menu.main]]
URL = "gallery"
name = "Gallery"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4


# default parameters
[params]
home = "Home"
logo = "images/astro_logo.png"
# theme color
theme_color = "#41228e"
# contact info
email = "astronomyclub@students.iiit.ac.in"

# contact
[params.contact]
enable = true

[[params.contact.coordinator]]
name = "Ansh Puvvada"
email = "ansh.puvvada@students.iiit.ac.in"

[[params.contact.coordinator]]
name = "Yash Chaurasia"
email = "yash.chaurasia@students.iiit.ac.in"
